name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test - ${{ matrix.platform }}
    # skip tests on draft PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release

  fmt:
    name: Format
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    # run fmt tests only on ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    # run fmt tests only on ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check clippy
        run: cargo clippy --all-targets --release -- -D warnings
